modify1127

diff --git a/.github/workflows/smart-contract-ci.yml b/.github/workflows/smart-contract-ci.yml
--- a/.github/workflows/smart-contract-ci.yml
+++ b/.github/workflows/smart-contract-ci.yml
@@ -1,78 +1,78 @@
-name: Smart Contract CI
+# name: Smart Contract CI
 
-on: 
-  push:
-    main
+# on: 
+#   push:
+#     main
     
-jobs:
-  cleanup-runs:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: rokroskar/workflow-run-cleanup-action@master
-        env:
-          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
-    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"
+# jobs:
+#   cleanup-runs:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - uses: rokroskar/workflow-run-cleanup-action@master
+#         env:
+#           GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
+#     if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"
 
-  build:
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        go-arch: ["amd64"]
-    steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-go@v4
-        with:
-          go-version: 1.18
-      - uses: technote-space/get-diff-action@v6.1.2
-        with:
-          PATTERNS: |
-            **/**.go
-            go.mod
-            go.sum
-            .github/workflows/test.yml
-      - name: Build
-        run: GOARCH=${{ matrix.go-arch }} LEDGER_ENABLED=false make build
-        if: env.GIT_DIFF
+#   build:
+#     runs-on: ubuntu-latest
+#     strategy:
+#       matrix:
+#         go-arch: ["amd64"]
+#     steps:
+#       - uses: actions/checkout@v3
+#       - uses: actions/setup-go@v4
+#         with:
+#           go-version: 1.18
+#       - uses: technote-space/get-diff-action@v6.1.2
+#         with:
+#           PATTERNS: |
+#             **/**.go
+#             go.mod
+#             go.sum
+#             .github/workflows/test.yml
+#       - name: Build
+#         run: GOARCH=${{ matrix.go-arch }} LEDGER_ENABLED=false make build
+#         if: env.GIT_DIFF
 
-  test-localnet-blocks:
-    runs-on: ubuntu-latest
-    needs: [build]
-    steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-go@v4
-        with:
-          go-version: 1.18
-      - uses: dsaltares/fetch-gh-release-asset@master
-        with:
-          repo: 'Finschia/cosmwasm'
-          version: 'latest'
-          regex: true
-          file: '.*'
-          target: 'contracts/'
+#   test-localnet-blocks:
+#     runs-on: ubuntu-latest
+#     needs: [build]
+#     steps:
+#       - uses: actions/checkout@v3
+#       - uses: actions/setup-go@v4
+#         with:
+#           go-version: 1.18
+#       - uses: dsaltares/fetch-gh-release-asset@master
+#         with:
+#           repo: 'Finschia/cosmwasm'
+#           version: 'latest'
+#           regex: true
+#           file: '.*'
+#           target: 'contracts/'
 
-      - name: Install docker-compose
-        run: sudo apt-get update && sudo apt-get install -y docker-compose
-      - name: build
-        run: |
-          make build
-          make install 
-      - name: Start localnet
-        run: |
-          ls -al 
-          make localnet-start
-      - name: Test smart contract
-        run: |
-          STORE_RES=$(fnsad tx wasm store contracts/queue.wasm --from alice --keyring-backend test --chain-id finschia --gas 1500000 -b block -o json -y)
-          sleep 10
-          echo $STORE_RES
-      - name: Stop localnet
-        run: |
-          make localnet-stop
-          if [ ${{ steps.test-blocks.outcome }} == 'failure' ] ; then
-            exit 1
-          fi
+#       - name: Install docker-compose
+#         run: sudo apt-get update && sudo apt-get install -y docker-compose
+#       - name: build
+#         run: |
+#           make build
+#           make install 
+#       - name: Start localnet
+#         run: |
+#           ls -al 
+#           make localnet-start
+#       - name: Test smart contract
+#         run: |
+#           STORE_RES=$(fnsad tx wasm store contracts/queue.wasm --from alice --keyring-backend test --chain-id finschia --gas 1500000 -b block -o json -y)
+#           sleep 10
+#           echo $STORE_RES
+#       - name: Stop localnet
+#         run: |
+#           make localnet-stop
+#           if [ ${{ steps.test-blocks.outcome }} == 'failure' ] ; then
+#             exit 1
+#           fi
 
-  # pull_smart_contract:
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - uses: actions/checkout@v3
+#   # pull_smart_contract:
+#   #   runs-on: ubuntu-latest
+#   #   steps:
+#   #     - uses: actions/checkout@v3
